In [2]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.10.0+cpu


In [3]:
import multiprocessing as mlt

print(mlt.cpu_count())

4


##  Introduction to Tensors

### Creating tensors

Tensors are created using torch.tensor

In [4]:
# scalar
scalar = torch.tensor(7)
print(scalar.ndim)
print(scalar.item()) # only works for scalars

0
7


In [5]:
# Vector
vector = torch.tensor([7,7])
print(vector.ndim)
print(vector.shape)


1
torch.Size([2])


In [6]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                        [9, 10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)


tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [7]:
MATRIX[1, 1]

tensor(10)

In [8]:

# TENSOR
TENSOR = torch.tensor([[[1, 2], 
                        [3, 4]], 
                        [[5, 6], 
                        [7, 8]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0, 1, 1])


tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
3
torch.Size([2, 2, 2])
tensor(4)


In [9]:
print(f'Tensor Columns: {TENSOR.shape[1]}')

Tensor Columns: 2


### Creating random tensors

In [8]:
random_tensor = torch.rand(3, 4, 3)
print(random_tensor)
print(random_tensor.ndim)

tensor([[[0.0477, 0.0504, 0.3720],
         [0.7243, 0.0617, 0.3690],
         [0.5005, 0.2074, 0.3800],
         [0.8240, 0.2267, 0.6572]],

        [[0.9768, 0.5025, 0.8525],
         [0.2469, 0.5421, 0.3342],
         [0.3889, 0.6996, 0.8596],
         [0.7278, 0.5171, 0.7089]],

        [[0.9025, 0.1564, 0.5311],
         [0.7574, 0.9771, 0.3810],
         [0.7532, 0.2318, 0.0273],
         [0.9906, 0.4201, 0.4353]]])
3


In [9]:
# rando tensor with similar shape to image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, channel
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [10]:
random_image_tensor

tensor([[[0.8469, 0.0044, 0.2036],
         [0.4146, 0.1714, 0.5385],
         [0.8768, 0.3399, 0.7240],
         ...,
         [0.0372, 0.3147, 0.4944],
         [0.0225, 0.8693, 0.9716],
         [0.1392, 0.5525, 0.5592]],

        [[0.3518, 0.1046, 0.4383],
         [0.1728, 0.4154, 0.2812],
         [0.5183, 0.7065, 0.2970],
         ...,
         [0.3803, 0.8720, 0.4782],
         [0.1743, 0.4864, 0.1771],
         [0.0608, 0.2913, 0.8324]],

        [[0.7850, 0.2001, 0.0533],
         [0.6787, 0.4894, 0.4041],
         [0.3639, 0.4959, 0.9769],
         ...,
         [0.9190, 0.2395, 0.5130],
         [0.5559, 0.7217, 0.5788],
         [0.8061, 0.5800, 0.1859]],

        ...,

        [[0.6513, 0.8898, 0.2467],
         [0.9261, 0.2046, 0.2021],
         [0.9425, 0.4634, 0.5045],
         ...,
         [0.0128, 0.4871, 0.1951],
         [0.6962, 0.3359, 0.3881],
         [0.2777, 0.7196, 0.8591]],

        [[0.8387, 0.3021, 0.0348],
         [0.8716, 0.5676, 0.1653],
         [0.

Creating tensors with ones and zeros

In [11]:
# Tensors with zeros
zeros = torch.zeros((3, 4), dtype=torch.half)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float16)

In [12]:
# Tensors with ones
ones = torch.ones(3, 4)
print(ones)
print(ones.dtype)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


## Creating a range of tensors and tensors-like

In [13]:
# torch.range()
arange = torch.arange(0,10, 2)
arange

tensor([0, 2, 4, 6, 8])

In [14]:
# Creating tensors like
zeros_like = torch.zeros_like(arange)
print(zeros_like) 

tensor([0, 0, 0, 0, 0])


## Tensor Datatypes


In [15]:
# Float32 tensor - default torch.float32 (single precision). other options: torch.float16 (half precision), torch.float64
float_32 = torch.tensor([3.0,6.0,9.0])
print(float_32.dtype)
float_16 = float_32.type(torch.half)
print(float_16.dtype)


torch.float32
torch.float16


In [16]:
float_64 = torch.tensor([3.0, 6.0, 9.0], 
                        dtype=torch.float64,    # what datatype is this tensor
                        device=None,            # which device this tensor is on
                        requires_grad=False)    # whether or not to track gradients with this tensor
float_64 

tensor([3., 6., 9.], dtype=torch.float64)

In [17]:
float_64 * float_16

tensor([ 9., 36., 81.], dtype=torch.float64)

### Manipulating tensors (tenosr operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication    (element-wise)
* Division
* Matrix multlication

In [18]:
# Tensor addition
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [19]:
# multiply tensor by ten
tensor * 10

tensor([10, 20, 30])

In [20]:
tensor

tensor([1, 2, 3])

In [21]:
# subtract by 10
tensor - 10


tensor([-9, -8, -7])

In [22]:
# In-built functions
torch.mul(tensor, 15)

tensor([15, 30, 45])

In [23]:
torch.add(tensor, 23)

tensor([24, 25, 26])

### matrix multiplication
* element-wise multiplication 
*  matrix multiplication (dot-product)

In [24]:
tensor = torch.rand(2, 3)
print(tensor)
print(tensor * 2)

tensor([[0.9149, 0.1162, 0.8871],
        [0.4925, 0.7752, 0.1041]])
tensor([[1.8298, 0.2324, 1.7742],
        [0.9850, 1.5505, 0.2083]])


In [25]:

tesor = torch.tensor([[2,3], 
                      [4,2]])
print(torch.matmul(tesor, tesor))
print(torch.matrix_power(tesor, 2))

tensor([[16, 12],
        [16, 16]])
tensor([[16, 12],
        [16, 16]])


#### Finding min, max, mean, sum, etc (tensor aggregation)

In [26]:
X = torch.arange(0,100,4, dtype=torch.float64)

print(X)
print(X.dtype)

tensor([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40., 44., 48., 52.,
        56., 60., 64., 68., 72., 76., 80., 84., 88., 92., 96.],
       dtype=torch.float64)
torch.float64


In [27]:
torch.min(X), X.min()

(tensor(0., dtype=torch.float64), tensor(0., dtype=torch.float64))

In [28]:
torch.max(X), X.max()

(tensor(96., dtype=torch.float64), tensor(96., dtype=torch.float64))

In [29]:
torch.mean(X)   # Note torch.mean() requires a tensor of floating datatype

tensor(48., dtype=torch.float64)

In [30]:
torch.sum(X), X.sum()

(tensor(1200., dtype=torch.float64), tensor(1200., dtype=torch.float64))

#### Finding positional min & max in tensors

In [31]:
print(X)
# Finds the position in tensor that has the minimum value with argmin -> returns the index 
print(X.argmin())

tensor([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40., 44., 48., 52.,
        56., 60., 64., 68., 72., 76., 80., 84., 88., 92., 96.],
       dtype=torch.float64)
tensor(0)


In [32]:
# Argmax
print(X.argmax())

tensor(24)



In [33]:
print(X[24])

tensor(96., dtype=torch.float64)


### Reshaping, Viewing, Stacking, squeezing & unsqueezing Tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (Vstack)
* Squeeze - remove all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [34]:
X = torch.arange(1.,10.)
print(X, X.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])


In [35]:
x_reshaped = X.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [36]:
# Change the view
z = X.view(1, 9)    # does the same thing as X.reshape, except that it shares the same memory with the original tensor
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [37]:
# Changing z changes x
z[:, 0] = -2
z, X

(tensor([[-2.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([-2.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [38]:
# Stacking tensors
x_stacked = torch.stack([X, X, X, X], dim=1)
x_stacked

tensor([[-2., -2., -2., -2.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.]])

In [39]:
#torch.hstack stacks tensors in sequence horizontally(column-wise)
x_stacked = torch.hstack([X,X,X,X])
x_stacked

tensor([-2.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., -2.,  2.,  3.,  4.,  5.,
         6.,  7.,  8.,  9., -2.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., -2.,
         2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [40]:
# torch.vstack stacks tensors in sequence vertically(row-wise)
x_stacked = torch.vstack([X,X,X,X])
x_stacked

tensor([[-2.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [-2.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [-2.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [-2.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [41]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f'x_reshaped: {x_reshaped}')
print(f'shape: {x_reshaped.shape}')

x_squeezed = x_reshaped.squeeze()
print(f'x_squeezed: {x_squeezed}')
print(f'Shape: {x_squeezed.shape}')

x_reshaped: tensor([[-2.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])
shape: torch.Size([1, 9])
x_squeezed: tensor([-2.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])
Shape: torch.Size([9])


In [42]:
    # torch.unsqueeze()
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[-2.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [43]:
#   torch.permute() - rearranges the dimensions of a target to tensor in a specified order
x = torch.randn(2,3,5)
print(x)
print(x.size())

x_permute = torch.permute(x, dims=(2,0,1))
print(f'Permuted tensor: {x_permute}')
print(f'Size: {x_permute.size()}')

tensor([[[ 0.1349,  0.5759, -0.5474,  0.1310,  2.5301],
         [ 0.2876, -0.1724, -1.0834, -0.1020, -0.9823],
         [ 0.2212,  0.0620,  0.1142, -0.5954, -1.3452]],

        [[-1.0080,  0.5245, -2.1653,  1.2694,  1.1173],
         [-1.0391,  0.5443,  0.9418,  0.9430, -0.6451],
         [-0.1392, -1.5858, -0.3940, -0.7531, -1.8086]]])
torch.Size([2, 3, 5])
Permuted tensor: tensor([[[ 0.1349,  0.2876,  0.2212],
         [-1.0080, -1.0391, -0.1392]],

        [[ 0.5759, -0.1724,  0.0620],
         [ 0.5245,  0.5443, -1.5858]],

        [[-0.5474, -1.0834,  0.1142],
         [-2.1653,  0.9418, -0.3940]],

        [[ 0.1310, -0.1020, -0.5954],
         [ 1.2694,  0.9430, -0.7531]],

        [[ 2.5301, -0.9823, -1.3452],
         [ 1.1173, -0.6451, -1.8086]]])
Size: torch.Size([5, 2, 3])


### Putting tensors on GPU



In [46]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [47]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [48]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [ ]:
X = torch.arange(0, 1, 0.02).unsqueeze(dim=0 )
X

tensor([[0.0000, 0.0200, 0.0400, 0.0600, 0.0800, 0.1000, 0.1200, 0.1400, 0.1600,
         0.1800, 0.2000, 0.2200, 0.2400, 0.2600, 0.2800, 0.3000, 0.3200, 0.3400,
         0.3600, 0.3800, 0.4000, 0.4200, 0.4400, 0.4600, 0.4800, 0.5000, 0.5200,
         0.5400, 0.5600, 0.5800, 0.6000, 0.6200, 0.6400, 0.6600, 0.6800, 0.7000,
         0.7200, 0.7400, 0.7600, 0.7800, 0.8000, 0.8200, 0.8400, 0.8600, 0.8800,
         0.9000, 0.9200, 0.9400, 0.9600, 0.9800]])