In [2]:
import torch
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('./iris-data.csv')
df.head()

,Unnamed: 0,sepal_length,sepal_width,petal_length,petal_widt,species
0,0,4.9,3.0,1.4,0.2,Iris-setosa
1,1,4.7,3.2,1.3,0.2,Iris-setosa
2,2,4.6,3.1,1.5,0.2,Iris-setosa
3,3,5.0,3.6,1.4,0.2,Iris-setosa
4,4,5.4,3.9,1.7,0.4,Iris-setosa


In [4]:
df = np.array(df)
df[0,:]

array([0, 4.9, 3.0, 1.4, 0.2, 'Iris-setosa'], dtype=object)

## Tensors: Multidimensional array(fundamental data structure in PyTorch)

In [5]:
tensor_1d = torch.tensor([1, 2, 3])
print("1D Tensor (Vector):")
print(tensor_1d)
print()
a = torch.ones(3)
print('1-D Tensor: ', a)
# print(a[2])
print()

tensor_2d = torch.tensor([[1, 2], [3, 4]])
print("2D Tensor (Matrix):")
print(tensor_2d)
print()

random_tensor = torch.rand(2,3, dtype=float)
print('Random Tensor (2x3):')
print(random_tensor)

1D Tensor (Vector):
tensor([1, 2, 3])

1-D Tensor:  tensor([1., 1., 1.])

2D Tensor (Matrix):
tensor([[1, 2],
        [3, 4]])

Random Tensor (2x3):
tensor([[0.0348, 0.0906, 0.4426],
        [0.6228, 0.3373, 0.4502]], dtype=torch.float64)


In [6]:
zeros_tensor = torch.zeros(2, 3)
print("Zeros Tensor (2x3):")
print(zeros_tensor)
print()

ones_tensor = torch.ones(2, 3)
print("Ones Tensor (2x3):")
print(ones_tensor)

## Creating tensor using shape dimension
shape = (2,3,)
tensor = torch.rand(shape)
print(tensor)
print(f'Tesnor shape: {tensor.shape}')
print(f'Tesnor datatype: {tensor.dtype}')
print(f'Tesnor device: {tensor.device}')

Zeros Tensor (2x3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones Tensor (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.1504, 0.6440, 0.1508],
        [0.7418, 0.5177, 0.4577]])
Tesnor shape: torch.Size([2, 3])
Tesnor datatype: torch.float32
Tesnor device: cpu


#### Tensor Operations(Indexing, Slicing, Reshaping)

In [7]:
##  Indexing &Slicing
print(random_tensor)
elements = random_tensor[0,:]
print(f'Sliced Tensor (first row): {elements}')

print('')

print(random_tensor)
element = random_tensor[0,1]
print(f'indexed element (first row, second column): {element}')

tensor([[0.0348, 0.0906, 0.4426],
        [0.6228, 0.3373, 0.4502]], dtype=torch.float64)
Sliced Tensor (first row): tensor([0.0348, 0.0906, 0.4426], dtype=torch.float64)

tensor([[0.0348, 0.0906, 0.4426],
        [0.6228, 0.3373, 0.4502]], dtype=torch.float64)
indexed element (first row, second column): 0.09060654513876021


In [8]:
## Reshaping
print(random_tensor)
print(random_tensor.size())
print('')
reshaped = random_tensor.view(3,2)

print(reshaped)
print(reshaped.size())

tensor([[0.0348, 0.0906, 0.4426],
        [0.6228, 0.3373, 0.4502]], dtype=torch.float64)
torch.Size([2, 3])

tensor([[0.0348, 0.0906],
        [0.4426, 0.6228],
        [0.3373, 0.4502]], dtype=torch.float64)
torch.Size([3, 2])


### Real-World Data Representation in Tensors

##### Working with image data
    An image is represented as a collection of scalars arranged in a regular grid with a height and a width (in pixels)

In [ ]:
import imageio
